name: "French Pressicus-Technicalus"
subtitle: "the common cafe nerd"
pygments: true
permalink: pretty
prose:
  # siteurl: 'http://edrex.github.io'
  relativeLinks: 'http://edrex.github.io/links.json'
  media: 'media'
me:
  name: Eric Drechsel
  profession: Science Hacker
  github: edrex
  twitter: edrex
